"""Show a failed run becoming a regression test without calling a model.

The scripted backend makes one fixed decision: call ``publish_report``
with revenue=120 and cost=80, then call ``done``. The v1 tool contains a
math bug. Captured-response replay feeds those exact model responses
through the fixed v2 tool in a fresh workspace. A host-side collector
reads ``report.json`` and the same required grader goes red, then green.

This is controlled harness re-execution, not deterministic simulation:
tool code executes again and any external side effects would be fresh.
"""

from __future__ import annotations

import argparse
import difflib
import json
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from looplet import (
    EvalHook,
    EvalResult,
    ProvenanceSink,
    cartridge_to_preset,
    load_cartridge_evals,
    replay_loop,
    save_eval_run,
    seed_case_workspace,
)
from looplet.testing import MockLLMBackend

HERE = Path(__file__).resolve().parent
SHIPPED_CARTRIDGE = HERE / "report_agent.cartridge"
BUGGY_TOOL = HERE / "before_publish_report.py"
FIXED_TOOL_REL = Path("tools/publish_report/execute.py")
MARKER = ".looplet-regression-demo"

MODEL_RESPONSES = [
    json.dumps(
        {
            "tool": "publish_report",
            "args": {"revenue": 120, "cost": 80},
            "reasoning": "publish the requested report",
        }
    ),
    json.dumps(
        {
            "tool": "done",
            "args": {"summary": "published report.json"},
            "reasoning": "the requested artifact exists",
        }
    ),
]


@dataclass(frozen=True)
class DemoResult:
    """Evidence produced by :func:`run_demo`."""

    output_dir: Path
    v1_score: float
    v2_score: float
    v1_report: dict[str, Any]
    v2_report: dict[str, Any]
    v1_tools: tuple[str, ...]
    v2_tools: tuple[str, ...]
    diff: str

    @property
    def same_model_decisions(self) -> bool:
        return self.v1_tools == self.v2_tools


def _reset_output(root: Path) -> None:
    """Reset a prior demo directory without deleting unrelated data."""
    if root.exists():
        entries = list(root.iterdir())
        if entries and not (root / MARKER).is_file():
            raise ValueError(
                f"refusing to replace non-demo directory {root}; choose an empty --out path"
            )
        shutil.rmtree(root)
    root.mkdir(parents=True)
    (root / MARKER).write_text("generated by examples/regression_demo/run_demo.py\n")


def _prepare_cartridges(root: Path) -> tuple[Path, Path]:
    v1 = root / "harness-v1.cartridge"
    v2 = root / "harness-v2.cartridge"
    shutil.copytree(SHIPPED_CARTRIDGE, v1)
    shutil.copytree(SHIPPED_CARTRIDGE, v2)
    shutil.copyfile(BUGGY_TOOL, v1 / FIXED_TOOL_REL)
    return v1, v2


def _case_and_task(cartridge: Path, runtime: dict[str, Any]):
    bundle = load_cartridge_evals(cartridge, runtime=runtime, strict=True)
    if len(bundle.cases) != 1:
        raise RuntimeError(f"expected one demo case, found {len(bundle.cases)}")
    case = bundle.cases[0]
    task = {key: value for key, value in case.task.items() if key != "files"}
    return bundle, case, task


def _required_score(results: list[EvalResult]) -> float:
    for result in results:
        if result.name == "eval_profit_is_correct":
            return float(result.score if result.score is not None else 0.0)
    raise RuntimeError("required grader eval_profit_is_correct did not run")


def _capture_v1(cartridge: Path, workspace: Path, run_dir: Path):
    runtime = {"project_root": str(workspace)}
    bundle, case, task = _case_and_task(cartridge, runtime)
    seed_case_workspace(case, workspace)
    preset = cartridge_to_preset(cartridge, runtime=runtime)
    eval_hook = EvalHook(
        evaluators=bundle.graders,
        collectors=bundle.collectors,
        expected=case.expected,
    )
    sink = ProvenanceSink(dir=run_dir)
    llm = sink.wrap_llm(MockLLMBackend(responses=list(MODEL_RESPONSES)))
    recorder = sink.trajectory_hook()
    preset.hooks = [*preset.hooks, recorder, eval_hook]
    try:
        steps = list(preset.run(llm, task=task))
    finally:
        preset.close()
    save_eval_run(run_dir, recorder=recorder, eval_hook=eval_hook, case=case)
    return case, steps, eval_hook


def _replay_v2(cartridge: Path, workspace: Path, source_run: Path, run_dir: Path):
    runtime = {"project_root": str(workspace)}
    bundle, case, task = _case_and_task(cartridge, runtime)
    seed_case_workspace(case, workspace)
    preset = cartridge_to_preset(cartridge, runtime=runtime)
    eval_hook = EvalHook(
        evaluators=bundle.graders,
        collectors=bundle.collectors,
        expected=case.expected,
    )
    hooks = [*preset.hooks, eval_hook]
    try:
        steps = list(
            replay_loop(
                source_run,
                tools=preset.tools,
                state=preset.state,
                hooks=hooks,
                config=preset.config,
                task=task,
            )
        )
    finally:
        preset.close()
    save_eval_run(run_dir, eval_hook=eval_hook, case=case)
    return steps, eval_hook


def run_demo(output_dir: str | Path | None = None) -> DemoResult:
    """Run the red-to-green proof and return its persisted evidence."""
    root = Path(output_dir or (Path(tempfile.gettempdir()) / "looplet-regression-demo"))
    _reset_output(root)
    v1_cartridge, v2_cartridge = _prepare_cartridges(root)

    workspaces = root / "workspaces"
    runs = root / "runs"
    v1_workspace = workspaces / "v1"
    v2_workspace = workspaces / "v2"
    v1_run = runs / "v1"
    v2_run = runs / "v2"

    _, v1_steps, v1_eval = _capture_v1(v1_cartridge, v1_workspace, v1_run)
    v2_steps, v2_eval = _replay_v2(v2_cartridge, v2_workspace, v1_run, v2_run)

    buggy = BUGGY_TOOL.read_text().splitlines(keepends=True)
    fixed = (SHIPPED_CARTRIDGE / FIXED_TOOL_REL).read_text().splitlines(keepends=True)
    diff = "".join(
        difflib.unified_diff(
            buggy,
            fixed,
            fromfile="tools/publish_report/execute.py (v1)",
            tofile="tools/publish_report/execute.py (v2)",
        )
    )

    return DemoResult(
        output_dir=root,
        v1_score=_required_score(v1_eval.results),
        v2_score=_required_score(v2_eval.results),
        v1_report=json.loads((v1_workspace / "report.json").read_text()),
        v2_report=json.loads((v2_workspace / "report.json").read_text()),
        v1_tools=tuple(step.tool_call.tool for step in v1_steps),
        v2_tools=tuple(step.tool_call.tool for step in v2_steps),
        diff=diff,
    )


def render(result: DemoResult) -> str:
    """Render a stable launch-friendly summary."""
    decisions = " -> ".join(result.v1_tools)
    return "\n".join(
        [
            "Looplet: one failed run -> one regression contract",
            "",
            "1. CAPTURE v1 with fixed model responses",
            f"   model decisions: {decisions}",
            f"   collected profit: {result.v1_report['profit']}",
            f"   required eval: FAIL ({result.v1_score:.2f})",
            "",
            "2. CHANGE one reviewable harness line",
            '   - "profit": revenue + cost,',
            '   + "profit": revenue - cost,',
            "",
            "3. REPLAY captured responses with fresh v2 tool execution",
            f"   same decisions: {str(result.same_model_decisions).lower()}",
            f"   collected profit: {result.v2_report['profit']}",
            f"   required eval: PASS ({result.v2_score:.2f})",
            "",
            f"Evidence: {result.output_dir}",
            "Replay holds model responses constant; tools and side effects execute again.",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, help="Evidence directory (default: system temp)")
    args = parser.parse_args(argv)
    result = run_demo(args.out)
    print(render(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
